/* =========================================================================
   AUDIO MAP — AUTO-GENERATED by scripts/generate_audio.js  (do not edit)
   Key:   the exact string of text to be spoken
   Value: relative path of the pre-generated .mp3 in public/assets/audio/
   While this map is empty (or a phrase is missing), the audio engine falls
   back to dynamic ElevenLabs requests, then to the browser voice.
   Run `npm run generate-audio` once to pre-generate every line.
   ========================================================================= */
export const audioMap = {};
